import { div } from "framer-motion/client";
import React, { useState, useEffect } from "react";
import { motion, number } from "framer-motion";

type FAQItem = {
  question: string;
  answer: string[];
};

const FAQData: FAQItem[] = [
  {
    question: "What is InvoiceLift and how does it work?",
    answer: [
      "InvoiceLift is a platform that turns business invoices into digital assets on Solana.",
      "This lets companies get quick funding from global investors while investors earn returns when the invoice is paid.",
      "InvoiceLift also tokenizes verified invoices into on-chain assets that can be funded by investors using stablecoins.",
    ],
  },
  {
    question: "How does InvoiceLift ensure the security and legitimacy of invoices?",
    answer: [
      "All invoices are checked using verification partners to make sure they are real.",
      "KYC/AML checks are also done to protect investors and the platform.",
      "InvoiceLift integrates verification oracles, identity checks, and compliance layers to confirm the validity of invoices.",
      " Only authenticated businesses and documents move forward in the financing process.",
    ],
  },
  {
    question: "How do investors earn returns on InvoiceLift?",
    answer: [
      "Investors fund invoices and earn profits when the business pays back the invoice. The returns depend on the discount rate and payment timeline.",
      "Investors purchase fractional or full positions in tokenized invoices at a discount. When the invoice matures and the buyer pays, smart contracts release the principal plus yield to the investor.",
      "Returns are generated by discount yield captured between the funding price and invoice face value.",
      ". Settlement is automated through Solana smart contracts, enabling predictable return flows and minimized counterparty risk.",
    ],
  },
  {
    question: "Why is InvoiceLift built on Solana?",
    answer: [
      "Solana is fast and cheap, so transactions are quick and cost almost nothing — perfect for invoice financing.",
      "Solana’s high throughput, low fees, and reliability make it ideal for real-time settlement, fractional trading, and global investor participation. This ensures a smooth and scalable financing experience.",
      "Solana provides high-performance execution, sub-second finality, and low-cost computation required for tokenization, automated escrows, and composable DeFi integrations. This allows InvoiceLift to operate as a programmable liquidity layer for trade finance.",
    ],
  },
];

export default function FAQ() {
  const [openIndex, setOpenIndex] = useState<number | null>(null);
  const [FAQcolor, setFAQcolor] = useState<boolean>(false);

  const FAQColorChange = () => {
    setFAQcolor(prev => !prev)
  }
  const toggle = (i: number) => {
    setOpenIndex((prev) => (prev === i ? null : i));
  };

  return (
    <div className="flex gap-20 flex-col xl:flex-row  items-center p-5">
      <div className="w-auto px-4 py-5 group bg-gradient-to-br from-white/5 to-white/0 backdrop-blur-sm rounded-2xl border border-gray-700/50 hover:border-purple-500/50 transition-all duration-300 hover:transform hover:scale-105 animate-fade-in">
        <h2 className={`text-2xl md:text-3xl font-bold ${FAQcolor ? 'text-green-500' : 'text-white'} transition-colors duration-300`}>
          <span className="hidden sm:block">Frequently Asked Questions</span>
          <span className="sm:hidden">FAQ</span>
        </h2>

        <div className="max-w-[600px] mt-8 rounded-lg shadow-[0_4px_50px_-8px_rgba(128,0,128,0.3)] text-[#1d3557] font-inter">
          {FAQData.map((item, i) => {
            const expanded = openIndex === i;

            useEffect(() => {
              if (expanded  !== null) {
                FAQColorChange();
              }
            }, [expanded]);

            return (
              <div key={i} className="border-b border-gray-200">
                {/* QUESTION */}
                <div
                  onClick={() => toggle(i)}
                  className="flex justify-between gap-8 text-[18px] font-semibold px-6 py-4 cursor-pointer"
                >
                  <span className={`${expanded ? 'text-green-500' : 'text-white'} transition-colors duration-300`}>{item.question}</span>

                  <span
                    className={`w-6 h-6 bg-gray-200 p-1 rounded-full flex transition-all duration-300 ${
                      expanded ? "bg-green-500 text-black rotate-180 transition-colors duration-300" : ""
                    }`}
                  >
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      fill="none"
                      viewBox="0 0 24 24"
                      strokeWidth={1.5}
                      stroke="currentColor"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        d="M19.5 8.25l-7.5 7.5-7.5-7.5"
                      />
                    </svg>
                  </span>
                </div>

                {/* ANSWER */}
                <motion.div
                  initial={{ height: 0, opacity: 0 }}
                  animate={expanded ? {height: "auto", opacity: 1} : {height: 0, opacity: 0}}
                  transition={{ duration: 0.3 }}
                  className="bg-[#1E1F3E] text-white rounded-bl-2xl rounded-br-2xl mb-2 border-l border-r border-b border-green-500 overflow-hidden transition-all ease-in-out duration-200 px-8"
                >
                  {item.answer.map((ans, idx) => (
                    <div key={idx} className="flex gap-2 my-2 hover:scale-105 cursor-default hover:font-bold transition-transform duration-200">
                      <span className="w-5 flex-shrink-0 text-green-600 mt-1 animate-UpDown">
                        <svg
                          xmlns="http://www.w3.org/2000/svg"
                          viewBox="0 0 20 20"
                          fill="currentColor"
                          className="w-5 h-5"
                        >
                          <path
                            fillRule="evenodd"
                            d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.857-9.809a.75.75 0 00-1.214-.882l-3.483 4.79-1.88-1.88a.75.75 0 10-1.06 1.061l2.5 2.5a.75.75 0 001.137-.089l4-5.5z"
                            clipRule="evenodd"
                          />
                        </svg>
                      </span>

                      <p className="leading-relaxed ">{ans}</p>
                    </div>
                  ))}
                </motion.div>
              </div>
            );
          })}
        </div>
      </div>


      <div className="p-5">
        <div className="">
          <p className='text-3xl md:text-4xl font-bold text-white mb-3'>
            <span className="">About Us</span>
          </p>
          <h2 className='sm:text-[16px] font-semibold text-[14px] text-white/90 uppercase tracking-wider'> The Future of Decentralized Finance on Solana, powered by invoice-backed liquidity.
          </h2>
        </div>

        <p className='mt-4 text-[17px] max-w-3xl leading-[30px] italic text-white/80'
        >
          At <span className="text-lg not-italic pl-1 text-[#8E32E9] font-bold">InvoiceLift</span> , we believe the future of decentralized finance on Solana is powered by invoice-backed liquidity. Our mission is to unlock real economic value by transforming unpaid invoices into liquid, tradable assets secured by on-chain rules.
          We provide businesses and investors with a transparent, fast, and secure marketplace where capital moves without friction. By combining Solana’s speed with institutional-grade infrastructure, we’re building a new financial layer that empowers global liquidity and DeFi growth.

        </p>
      </div>
    </div>
  );
}